# Site settings
title: Jake's Blog
email: blog-contact@ja-ke.tech
desc: All about eletronics and software
description: > # this means to ignore newlines until "baseurl:"
url: "http://blog.ja-ke.tech" # the base hostname & protocol for your site
github_username:  Jakeler

# Build settings
paginate: 4

author: Jake

theme: minima
